### ISSUE TITLE
Submit to packagist

### ISSUE THREAD

**Issue by RickDBCN** [webwinkelkeur/magento2#23]
Hi there!

Is there any chance you could submit this repository to packagist?

**Comment by apeschar** [comment]
Because of the build process we use to generate two separate modules for [WebwinkelKeur](https://www.webwinkelkeur.nl/) and [TrustProfile](https://www.trustprofile.com/) this repository is not directly installable using Composer.

You should be able to install the extension using Composer after adding it to your Magento marketplace account.
